Repository artichoke/rand_mt, pull requests merged in 2021-11, with the labels that each got.

#111 Update Audit GitHub Actions workflow
  .github/workflows/audit.yaml
Labels: A-build

#112 Update version-sync to 0.9.3 and trim some deps from Cargo.lock
  Cargo.toml
Labels: A-deps

#113 Add GitHub Actions workflow to run markdown-link-check
  .github/workflows/markdown-link-check.yaml
Labels: C-quality, C-docs, A-build

#115 Update markdown-link-check.yaml
  .github/workflows/markdown-link-check.yaml
Labels: A-build

#116 Replaces hand-rolled loops in `fill_bytes` with `chunks_exact_mut`
  src/mt.rs
  src/mt64.rs
Labels: C-quality, A-core, A-performance

#117 Fix typo in comment in benchmarks
  benches/benchmarks.rs
Labels: C-quality

#118 Fix Apache 2.0 license
  LICENSE-APACHE
Labels: A-project, A-packaging

#119 Unconditionally make crate 'no_std'
  src/lib.rs
Labels: C-quality, A-crate-features

#120 Release v4.1.0
  Cargo.toml
  README.md
  src/lib.rs
Labels: A-release
